# **Lab 2.2: Preprocessing**

<hr>

## **1. Objective**
In this lab, we will download a dataset, analyze it, and clean it for use in future labs.

### **Pandas Library**
It is considered the most popular data analysis library in Python.
It performs all its operations using a *"DataFrame"* object.

It allows, among other operations:  

* Loading and storing data in different formats (csv, tsv, xlsx, txt...).  
* Manipulating rows, columns, and cells.  
* Filtering or grouping content.  
* Performing intersection, concatenation, or merging of multiple DataFrames.  

To install it:

In [1]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\uo293747\.conda\envs\ssii\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\uo293747\.conda\envs\ssii\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.3 MB 15.0 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.3 MB 29.9 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 28.4 MB/s  0:00:00
Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 12.9/12.9 MB 89.7 MB/s  0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2025.2 tzdata-2025.3

<div class="alert alert-block alert-warning">  
    <strong>NOTE:</strong> The exclamation mark before the code indicates to Jupyter that this is not Python and should be executed in the terminal. This allows us to install libraries directly from the notebook.
</div>

<hr>

## **2. Exploratory Data Analysis (EDA)**

The main objectives of this analysis are:
* Understand the data we will be working with.
* Clean the dataset:
  * Remove empty rows or columns.
  * Eliminate inconsistent values.

Our dataset contains information about a race from the 2023 Formula 1 season.
Next, we will download the data and analyze it using the Pandas library.

In [2]:
import pandas as pd

url_data = 'https://raw.githubusercontent.com/AIC-Uniovi/Sistemas-Inteligentes/refs/heads/main/datasets/f1_23_monaco.csv'
data = pd.read_csv(url_data)

**Description of Dataset Columns**

| Column               | Description |
|----------------------|------------|
| `Time`              | Total elapsed time in the session. |
| `Driver`            | Three-letter driver code. |
| `DriverNumber`      | Driver's race number. |
| `LapTime`           | Total lap time. |
| `LapNumber`         | Lap number in the session. |
| `Stint`             | Current stint number (period between pit stops). |
| `PitOutTime`        | Time when the driver exited the pit lane. |
| `PitInTime`         | Time when the driver entered the pit lane. |
| `Sector1Time`       | Time recorded in the first sector of the lap. |
| `Sector2Time`       | Time recorded in the second sector of the lap. |
| `Sector3Time`       | Time recorded in the third sector of the lap. |
| `SpeedI1`           | Speed measured at the first detection point. |
| `SpeedI2`           | Speed measured at the second detection point. |
| `SpeedFL`           | Speed at the finish line. |
| `SpeedST`           | Maximum speed in the sector. |
| `IsPersonalBest`    | Indicates if the lap is the driver's personal best (`True`/`False`). |
| `Compound`          | Type of tire compound used. |
| `TyreLife`          | Number of laps the tire has been used. |
| `FreshTyre`         | Indicates if the tire was new at the start of the lap (`True`/`False`). |
| `Team`              | Driver's team name. |
| `LapStartTime`      | Lap start time within the session. |
| `LapStartDate`      | Exact date and time of lap start. |
| `TrackStatus`       | Track condition during the lap (e.g., yellow flag, green flag, etc.). |
| `Position`          | Driver's position at the end of the lap. |
| `Deleted`           | Indicates if the lap was deleted (`True`/`False`). |
| `DeletedReason`     | Reason why the lap was deleted (if applicable). |
| `IsAccurate`        | Indicates if the lap data is accurate (`True`/`False`). |

### **Basic Operations**

In [3]:
# Column names
data.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'IsAccurate'],
      dtype='object')

In [4]:
# Column types
data.dtypes

Time               object
Driver             object
DriverNumber        int64
LapTime            object
LapNumber         float64
Stint             float64
PitOutTime         object
PitInTime          object
Sector1Time        object
Sector2Time        object
Sector3Time        object
SpeedI1           float64
SpeedI2           float64
SpeedFL           float64
SpeedST           float64
IsPersonalBest       bool
Compound           object
TyreLife          float64
FreshTyre            bool
Team               object
LapStartTime       object
LapStartDate       object
TrackStatus         int64
Position          float64
Deleted              bool
DeletedReason      object
IsAccurate           bool
dtype: object

In [5]:
# Number of columns
len(data.columns)

27

In [6]:
# Number of rows
len(data)

1513

In [7]:
# Get basic statistics for the entire dataset  
data.describe()

,DriverNumber,LapNumber,Stint,SpeedI1,SpeedI2,SpeedFL,SpeedST,TyreLife,TrackStatus,Position
count,1513.000000,1513.000000,1513.000000,1391.000000,1513.000000,1476.000000,1513.000000,1513.000000,1513.000000,1513.000000
mean,28.438863,38.523463,1.775942,175.464414,173.806345,257.080623,272.918705,19.269002,2.851950,10.262393
std,23.285504,22.125804,0.942474,28.337102,21.097378,7.230135,13.549024,13.872089,4.798371,5.671148
min,1.000000,1.000000,1.000000,90.000000,79.000000,187.000000,157.000000,1.000000,1.000000,1.000000
25%,11.000000,19.000000,1.000000,151.000000,162.000000,256.000000,271.000000,8.000000,1.000000,5.000000
50%,22.000000,38.000000,1.000000,189.000000,184.000000,258.000000,278.000000,16.000000,1.000000,10.000000
75%,44.000000,57.000000,2.000000,197.000000,189.000000,259.000000,280.000000,28.000000,1.000000,15.000000
max,81.000000,78.000000,6.000000,212.000000,197.000000,272.000000,288.000000,56.000000,21.000000,20.000000

In [8]:
# Find columns with missing values
data.isnull().any()

Time              False
Driver            False
DriverNumber      False
LapTime            True
LapNumber         False
Stint             False
PitOutTime         True
PitInTime          True
Sector1Time        True
Sector2Time       False
Sector3Time       False
SpeedI1            True
SpeedI2           False
SpeedFL            True
SpeedST           False
IsPersonalBest    False
Compound          False
TyreLife          False
FreshTyre         False
Team              False
LapStartTime      False
LapStartDate      False
TrackStatus       False
Position          False
Deleted           False
DeletedReason      True
IsAccurate        False
dtype: bool

In [9]:
# Display the first 5 rows
data.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
0,0 days 01:03:27.458000,VER,1,0 days 00:01:24.238000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:37.420000,...,1.0,True,Red Bull Racing,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,1.0,False,NaN,False
1,0 days 01:04:46.825000,VER,1,0 days 00:01:19.367000,2.0,1.0,NaN,NaN,0 days 00:00:20.954000,0 days 00:00:37.366000,...,2.0,True,Red Bull Racing,0 days 01:03:27.458000,2023-05-28 13:04:28.435,1,1.0,False,NaN,True
2,0 days 01:06:05.899000,VER,1,0 days 00:01:19.074000,3.0,1.0,NaN,NaN,0 days 00:00:20.854000,0 days 00:00:37.288000,...,3.0,True,Red Bull Racing,0 days 01:04:46.825000,2023-05-28 13:05:47.802,1,1.0,False,NaN,True
3,0 days 01:07:24.028000,VER,1,0 days 00:01:18.129000,4.0,1.0,NaN,NaN,0 days 00:00:20.835000,0 days 00:00:36.637000,...,4.0,True,Red Bull Racing,0 days 01:06:05.899000,2023-05-28 13:07:06.876,1,1.0,False,NaN,True
4,0 days 01:08:42.047000,VER,1,0 days 00:01:18.019000,5.0,1.0,NaN,NaN,0 days 00:00:20.745000,0 days 00:00:36.734000,...,5.0,True,Red Bull Racing,0 days 01:07:24.028000,2023-05-28 13:08:25.005,1,1.0,False,NaN,True

In [10]:
# Display the last 5 rows
data.tail(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
1508,0 days 02:45:26.431000,PIA,81,0 days 00:01:27.443000,73.0,2.0,NaN,NaN,0 days 00:00:23.295000,0 days 00:00:42.212000,...,19.0,True,McLaren,0 days 02:43:58.988000,2023-05-28 14:44:59.965,1,10.0,False,NaN,True
1509,0 days 02:46:52.616000,PIA,81,0 days 00:01:26.185000,74.0,2.0,NaN,NaN,0 days 00:00:22.381000,0 days 00:00:42.112000,...,20.0,True,McLaren,0 days 02:45:26.431000,2023-05-28 14:46:27.408,1,10.0,False,NaN,True
1510,0 days 02:48:18.759000,PIA,81,0 days 00:01:26.143000,75.0,2.0,NaN,NaN,0 days 00:00:22.061000,0 days 00:00:42.272000,...,21.0,True,McLaren,0 days 02:46:52.616000,2023-05-28 14:47:53.593,1,10.0,False,NaN,True
1511,0 days 02:49:44.374000,PIA,81,0 days 00:01:25.615000,76.0,2.0,NaN,NaN,0 days 00:00:21.991000,0 days 00:00:41.496000,...,22.0,True,McLaren,0 days 02:48:18.759000,2023-05-28 14:49:19.736,1,10.0,False,NaN,True
1512,0 days 02:51:09.159000,PIA,81,0 days 00:01:24.785000,77.0,2.0,NaN,NaN,0 days 00:00:21.970000,0 days 00:00:40.944000,...,23.0,True,McLaren,0 days 02:49:44.374000,2023-05-28 14:50:45.351,1,10.0,False,NaN,True

In [11]:
# Access a specific column 
data['Driver']

0       VER
1       VER
2       VER
3       VER
4       VER
       ...
1508    PIA
1509    PIA
1510    PIA
1511    PIA
1512    PIA
Name: Driver, Length: 1513, dtype: object

In [12]:
# Get multiple statistics for a column
data['Stint'].describe()

count    1513.000000
mean        1.775942
std         0.942474
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         6.000000
Name: Stint, dtype: float64

In [13]:
# Operations on numeric columns
data['LapNumber'] + 1

0        2.0
1        3.0
2        4.0
3        5.0
4        6.0
        ...
1508    74.0
1509    75.0
1510    76.0
1511    77.0
1512    78.0
Name: LapNumber, Length: 1513, dtype: float64

In [14]:
# View unique (non-repeating) values of a column
data['Team'].unique()

array(['Red Bull Racing', 'Alpine', 'Aston Martin', 'Ferrari', 'Williams',
       'Haas F1 Team', 'AlphaTauri', 'Alfa Romeo', 'McLaren', 'Mercedes'],
      dtype=object)

In [15]:
len(data['Team'].unique())

10

In [25]:
# Access multiple columns
data[['Driver', 'Team']]

     Driver             Team
0       VER  Red Bull Racing
1       VER  Red Bull Racing
2       VER  Red Bull Racing
3       VER  Red Bull Racing
4       VER  Red Bull Racing
...     ...              ...
1508    PIA          McLaren
1509    PIA          McLaren
1510    PIA          McLaren
1511    PIA          McLaren
1512    PIA          McLaren

[1513 rows x 2 columns]

In [17]:
# Get a list of values from a column and access aneElement
data['Team'].values[180]

'Red Bull Racing'

In [18]:
# Access row 1280, column 1 (zero-indexed)
data.iloc[1280, 1]

'SAI'

In [19]:
# Sort by the 'LapTime' column
data.sort_values(['LapTime'])

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
1157,0 days 01:45:31.903000,HAM,44,0 days 00:01:15.650000,33.0,2.0,NaN,NaN,0 days 00:00:19.760000,0 days 00:00:35.647000,...,2.0,True,Mercedes,0 days 01:44:16.253000,2023-05-28 13:45:17.230,1,8.0,False,NaN,True
355,0 days 02:02:23.489000,LEC,16,0 days 00:01:15.773000,46.0,2.0,NaN,NaN,0 days 00:00:19.996000,0 days 00:00:35.718000,...,2.0,True,Ferrari,0 days 02:01:07.716000,2023-05-28 14:02:08.693,1,8.0,False,NaN,True
126,0 days 02:06:14.872000,GAS,10,0 days 00:01:15.831000,49.0,2.0,NaN,NaN,0 days 00:00:19.843000,0 days 00:00:35.692000,...,2.0,True,Alpine,0 days 02:04:59.041000,2023-05-28 14:06:00.018,1,8.0,False,NaN,True
127,0 days 02:07:30.827000,GAS,10,0 days 00:01:15.955000,50.0,2.0,NaN,NaN,0 days 00:00:20.045000,0 days 00:00:35.628000,...,3.0,True,Alpine,0 days 02:06:14.872000,2023-05-28 14:07:15.849,1,8.0,False,NaN,True
359,0 days 02:07:29.057000,LEC,16,0 days 00:01:15.956000,50.0,2.0,NaN,NaN,0 days 00:00:19.730000,0 days 00:00:35.934000,...,6.0,True,Ferrari,0 days 02:06:13.101000,2023-05-28 14:07:14.078,1,7.0,False,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,0 days 02:38:48.233000,TSU,22,0 days 00:02:17.012000,68.0,2.0,NaN,NaN,0 days 00:00:25.629000,0 days 00:01:21.925000,...,15.0,True,AlphaTauri,0 days 02:36:31.221000,2023-05-28 14:37:32.198,12,13.0,False,NaN,True
1257,0 days 02:15:32.997000,SAI,55,0 days 00:02:19.381000,55.0,2.0,NaN,0 days 02:15:04.653000,0 days 00:00:27.227000,0 days 00:01:01.073000,...,22.0,True,Ferrari,0 days 02:13:13.616000,2023-05-28 14:14:14.593,12,8.0,False,NaN,False
947,0 days 02:15:34.526000,HUL,27,0 days 00:02:19.643000,54.0,2.0,NaN,0 days 02:15:00.544000,0 days 00:00:27.923000,0 days 00:00:56.020000,...,53.0,True,Haas F1 Team,0 days 02:13:14.883000,2023-05-28 14:14:15.860,12,18.0,False,NaN,False
574,0 days 02:24:30.971000,MAG,20,0 days 00:02:26.648000,58.0,2.0,NaN,NaN,0 days 00:01:08.435000,0 days 00:00:50.544000,...,2.0,True,Haas F1 Team,0 days 02:22:04.323000,2023-05-28 14:23:05.300,12,19.0,False,NaN,True
572,0 days 02:20:16.305000,MAG,20,NaN,56.0,1.0,NaN,0 days 02:19:25.914000,0 days 00:00:38.677000,0 days 00:01:03.774000,...,56.0,True,Haas F1 Team,0 days 02:17:04.203000,2023-05-28 14:18:05.180,12,19.0,False,NaN,False

<div class='alert alert-block alert-warning'>
    <strong>NOTE:</strong> The previous operations are not 'inplace', meaning they do not modify the DataFrame, they only query it.
</div>

In [20]:
# Get the maximum, mean, and minimum number of laps a set of tires was used
mean_life = data['TyreLife'].mean()
min_life = data['TyreLife'].min()
max_life = data['TyreLife'].max()

print(min_life, mean_life, max_life)

1.0 19.2690019828156 56.0

In [21]:
# Change the type of a series of columns to int
data[['DriverNumber', 'LapNumber', 'Stint', 'TyreLife', 'TrackStatus', 'Position']] = data[['DriverNumber', 'LapNumber', 'Stint', 'TyreLife', 'TrackStatus', 'Position']].astype(int)

In [22]:
# Add a new column
data['New_Column_1'] = 1 # All rows will have the same value
data['New_Column_2'] = list(range(len(data))) # New column created from a list of values (as many as rows)
data['New_Column_3'] = data['Stint'] + 1 # New column created from another column

In [23]:
# Delete columns
data = data.drop(columns = ['New_Column_1', 'New_Column_2', 'New_Column_3'])
# This is equivalent to:
# data.drop(columns = ['New_Column_1', 'New_Column_2', 'New_Column_3'], inplace = True)

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Get the number of unique drivers.
</div>

In [ ]:
# Your code here
len(data['Driver'].unique())

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Change the type of the columns: "Time", "LapTime", "PitOutTime", "PitInTime", "Sector1Time", "Sector2Time", "Sector3Time" and "LapStartTime" to <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_timedelta.html"><i>timedelta</i></a>.
</div>

In [42]:
time_columns = ['Time', 'LapTime', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'LapStartTime']
# Your code here
for i in data[time_columns].values:
    pd.to_timedelta(i)

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Change the type of the column: 'LapStartDate' to <a href="https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html"><i>datetime</i></a>.
</div>

In [ ]:
# Your code here
pd.to_datetime(data['LapStartDate'])

0      2023-05-28 13:03:03.927
1      2023-05-28 13:04:28.435
2      2023-05-28 13:05:47.802
3      2023-05-28 13:07:06.876
4      2023-05-28 13:08:25.005
                 ...
1508   2023-05-28 14:44:59.965
1509   2023-05-28 14:46:27.408
1510   2023-05-28 14:47:53.593
1511   2023-05-28 14:49:19.736
1512   2023-05-28 14:50:45.351
Name: LapStartDate, Length: 1513, dtype: datetime64[ns]

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Which driver has been the best in the first sector? And in the second sector?
</div>

In [39]:
# Your code here
print(data.sort_values(['Sector1Time']).head(1)['Driver'])

print(data.sort_values(['Sector2Time']).head(1)['Driver'])

359    LEC
Name: Driver, dtype: object
127    GAS
Name: Driver, dtype: object

### **Data Filtering**

In [43]:
# Get the value of a specific cell
data.loc[572, 'Team']

'Haas F1 Team'

In [44]:
# Get the laps of drivers whose team is 'Ferrari'
data_ferrari = data.loc[data['Team'] == 'Ferrari']
data_ferrari

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
310,0 days 01:03:32.328000,LEC,16,0 days 00:01:29.108000,1,1,NaN,NaN,NaN,0 days 00:00:38.983000,...,1,True,Ferrari,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,6,False,NaN,False
311,0 days 01:04:52.877000,LEC,16,0 days 00:01:20.549000,2,1,NaN,NaN,0 days 00:00:21.352000,0 days 00:00:37.692000,...,2,True,Ferrari,0 days 01:03:32.328000,2023-05-28 13:04:33.305,1,6,False,NaN,True
312,0 days 01:06:12.898000,LEC,16,0 days 00:01:20.021000,3,1,NaN,NaN,0 days 00:00:21.051000,0 days 00:00:37.547000,...,3,True,Ferrari,0 days 01:04:52.877000,2023-05-28 13:05:53.854,1,6,False,NaN,True
313,0 days 01:07:32.366000,LEC,16,0 days 00:01:19.468000,4,1,NaN,NaN,0 days 00:00:21.023000,0 days 00:00:37.375000,...,4,True,Ferrari,0 days 01:06:12.898000,2023-05-28 13:07:13.875,1,6,False,NaN,True
314,0 days 01:08:51.203000,LEC,16,0 days 00:01:18.837000,5,1,NaN,NaN,0 days 00:00:20.803000,0 days 00:00:37.198000,...,5,True,Ferrari,0 days 01:07:32.366000,2023-05-28 13:08:33.343,1,6,False,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1276,0 days 02:46:14.565000,SAI,55,0 days 00:01:28.585000,74,3,NaN,NaN,0 days 00:00:24.031000,0 days 00:00:42.481000,...,19,True,Ferrari,0 days 02:44:45.980000,2023-05-28 14:45:46.957,1,8,False,NaN,True
1277,0 days 02:47:40.953000,SAI,55,0 days 00:01:26.388000,75,3,NaN,NaN,0 days 00:00:22.468000,0 days 00:00:41.871000,...,20,True,Ferrari,0 days 02:46:14.565000,2023-05-28 14:47:15.542,1,8,False,NaN,True
1278,0 days 02:49:06.729000,SAI,55,0 days 00:01:25.776000,76,3,NaN,NaN,0 days 00:00:22.362000,0 days 00:00:41.296000,...,21,True,Ferrari,0 days 02:47:40.953000,2023-05-28 14:48:41.930,1,8,False,NaN,True
1279,0 days 02:50:32.308000,SAI,55,0 days 00:01:25.579000,77,3,NaN,NaN,0 days 00:00:22.283000,0 days 00:00:41.078000,...,22,True,Ferrari,0 days 02:49:06.729000,2023-05-28 14:50:07.706,1,8,False,NaN,True
1280,0 days 02:51:58.591000,SAI,55,0 days 00:01:26.283000,78,3,NaN,NaN,0 days 00:00:22.537000,0 days 00:00:41.195000,...,23,True,Ferrari,0 days 02:50:32.308000,2023-05-28 14:51:33.285,1,8,False,NaN,True

In [45]:
# Get all laps 1 and 2 of the drivers
data.loc[data['LapNumber'] <= 2]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
0,0 days 01:03:27.458000,VER,1,0 days 00:01:24.238000,1,1,NaN,NaN,NaN,0 days 00:00:37.420000,...,1,True,Red Bull Racing,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,1,False,NaN,False
1,0 days 01:04:46.825000,VER,1,0 days 00:01:19.367000,2,1,NaN,NaN,0 days 00:00:20.954000,0 days 00:00:37.366000,...,2,True,Red Bull Racing,0 days 01:03:27.458000,2023-05-28 13:04:28.435,1,1,False,NaN,True
78,0 days 01:03:32.921000,GAS,10,0 days 00:01:29.701000,1,1,NaN,NaN,NaN,0 days 00:00:39.087000,...,1,True,Alpine,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,7,False,NaN,False
79,0 days 01:04:53.557000,GAS,10,0 days 00:01:20.636000,2,1,NaN,NaN,0 days 00:00:21.350000,0 days 00:00:37.855000,...,2,True,Alpine,0 days 01:03:32.921000,2023-05-28 13:04:33.898,1,7,False,NaN,True
156,0 days 01:04:01.410000,PER,11,0 days 00:01:58.190000,1,1,NaN,0 days 01:03:37.245000,NaN,0 days 00:00:45.390000,...,1,True,Red Bull Racing,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,18,False,NaN,False
157,0 days 01:05:21.114000,PER,11,0 days 00:01:19.704000,2,2,0 days 01:04:02.058000,NaN,0 days 00:00:22.935000,0 days 00:00:36.337000,...,1,True,Red Bull Racing,0 days 01:04:01.410000,2023-05-28 13:05:02.387,1,18,False,NaN,False
232,0 days 01:03:28.747000,ALO,14,0 days 00:01:25.527000,1,1,NaN,NaN,NaN,0 days 00:00:37.981000,...,2,False,Aston Martin,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,2,False,NaN,False
233,0 days 01:04:48.393000,ALO,14,0 days 00:01:19.646000,2,1,NaN,NaN,0 days 00:00:20.871000,0 days 00:00:37.656000,...,3,False,Aston Martin,0 days 01:03:28.747000,2023-05-28 13:04:29.724,1,2,False,NaN,True
310,0 days 01:03:32.328000,LEC,16,0 days 00:01:29.108000,1,1,NaN,NaN,NaN,0 days 00:00:38.983000,...,1,True,Ferrari,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,6,False,NaN,False
311,0 days 01:04:52.877000,LEC,16,0 days 00:01:20.549000,2,1,NaN,NaN,0 days 00:00:21.352000,0 days 00:00:37.692000,...,2,True,Ferrari,0 days 01:03:32.328000,2023-05-28 13:04:33.305,1,6,False,NaN,True
388,0 days 01:03:42.782000,STR,18,0 days 00:01:39.562000,1,1,NaN,NaN,NaN,0 days 00:00:46.215000,...,2,False,Aston Martin,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,17,False,NaN,False
389,0 days 01:05:02.771000,STR,18,0 days 00:01:19.989000,2,1,NaN,NaN,0 days 00:00:21.136000,0 days 00:00:37.566000,...,3,False,Aston Martin,0 days 01:03:42.782000,2023-05-28 13:04:43.759,1,17,False,NaN,True
441,0 days 01:03:40.909000,SAR,2,0 days 00:01:37.689000,1,1,NaN,NaN,NaN,0 days 00:00:44.183000,...,1,True,Williams,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,15,False,NaN,False
442,0 days 01:05:00.567000,SAR,2,0 days 00:01:19.658000,2,1,NaN,NaN,0 days 00:00:21.209000,0 days 00:00:37.307000,...,2,True,Williams,0 days 01:03:40.909000,2023-05-28 13:04:41.886,1,15,False,NaN,True
517,0 days 01:03:41.645000,MAG,20,0 days 00:01:38.425000,1,1,NaN,NaN,NaN,0 days 00:00:43.991000,...,1,True,Haas F1 Team,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,16,False,NaN,False
518,0 days 01:05:01.820000,MAG,20,0 days 00:01:20.175000,2,1,NaN,NaN,0 days 00:00:20.988000,0 days 00:00:37.573000,...,2,True,Haas F1 Team,0 days 01:03:41.645000,2023-05-28 13:04:42.622,1,16,False,NaN,True
587,0 days 01:03:36.669000,DEV,21,0 days 00:01:33.449000,1,1,NaN,NaN,NaN,0 days 00:00:40.159000,...,1,True,AlphaTauri,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,12,False,NaN,False
588,0 days 01:04:58.433000,DEV,21,0 days 00:01:21.764000,2,1,NaN,NaN,0 days 00:00:21.649000,0 days 00:00:38.019000,...,2,True,AlphaTauri,0 days 01:03:36.669000,2023-05-28 13:04:37.646,1,12,False,NaN,True
664,0 days 01:03:34.537000,TSU,22,0 days 00:01:31.317000,1,1,NaN,NaN,NaN,0 days 00:00:39.573000,...,1,True,AlphaTauri,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,9,False,NaN,False
665,0 days 01:04:55.825000,TSU,22,0 days 00:01:21.288000,2,1,NaN,NaN,0 days 00:00:21.766000,0 days 00:00:37.771000,...,2,True,AlphaTauri,0 days 01:03:34.537000,2023-05-28 13:04:35.514,1,9,False,NaN,True
740,0 days 01:03:37.836000,ALB,23,0 days 00:01:34.616000,1,1,NaN,NaN,NaN,0 days 00:00:41.843000,...,1,True,Williams,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,13,False,NaN,False
741,0 days 01:04:58.813000,ALB,23,0 days 00:01:20.977000,2,1,NaN,NaN,0 days 00:00:21.337000,0 days 00:00:37.926000,...,2,True,Williams,0 days 01:03:37.836000,2023-05-28 13:04:38.813,1,13,False,NaN,True
817,0 days 01:04:02.005000,ZHO,24,0 days 00:01:58.785000,1,1,NaN,0 days 01:03:36.589000,NaN,0 days 00:00:44.973000,...,1,True,Alfa Romeo,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,19,False,NaN,False
818,0 days 01:05:22.762000,ZHO,24,0 days 00:01:20.757000,2,2,0 days 01:04:02.714000,NaN,0 days 00:00:23.917000,0 days 00:00:36.293000,...,1,True,Alfa Romeo,0 days 01:04:02.005000,2023-05-28 13:05:02.982,1,19,False,NaN,False
894,0 days 01:04:03.312000,HUL,27,0 days 00:02:00.092000,1,1,NaN,0 days 01:03:31.449000,NaN,0 days 00:00:41.349000,...,1,True,Haas F1 Team,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,20,False,NaN,False
895,0 days 01:05:23.746000,HUL,27,0 days 00:01:20.434000,2,2,0 days 01:04:03.995000,NaN,0 days 00:00:23.288000,0 days 00:00:36.554000,...,1,True,Haas F1 Team,0 days 01:04:03.312000,2023-05-28 13:05:04.289,1,20,False,NaN,False
970,0 days 01:03:29.859000,OCO,31,0 days 00:01:26.639000,1,1,NaN,NaN,NaN,0 days 00:00:38.186000,...,1,True,Alpine,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,3,False,NaN,False
971,0 days 01:04:50.160000,OCO,31,0 days 00:01:20.301000,2,1,NaN,NaN,0 days 00:00:21.245000,0 days 00:00:37.737000,...,2,True,Alpine,0 days 01:03:29.859000,2023-05-28 13:04:30.836,1,3,False,NaN,True
1048,0 days 01:03:35.254000,NOR,4,0 days 00:01:32.034000,1,1,NaN,NaN,NaN,0 days 00:00:39.590000,...,1,True,McLaren,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,10,False,NaN,False
1049,0 days 01:04:56.864000,NOR,4,0 days 00:01:21.610000,2,1,NaN,NaN,0 days 00:00:21.769000,0 days 00:00:38.014000,...,2,True,McLaren,0 days 01:03:35.254000,2023-05-28 13:04:36.231,1,10,False,NaN,True
1125,0 days 01:03:31.805000,HAM,44,0 days 00:01:28.585000,1,1,NaN,NaN,NaN,0 days 00:00:38.830000,...,1,True,Mercedes,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,5,False,NaN,False
1126,0 days 01:04:52.332000,HAM,44,0 days 00:01:20.527000,2,1,NaN,NaN,0 days 00:00:21.226000,0 days 00:00:37.769000,...,2,True,Mercedes,0 days 01:03:31.805000,2023-05-28 13:04:32.782,1,5,False,NaN,True
1203,0 days 01:03:30.610000,SAI,55,0 days 00:01:27.390000,1,1,NaN,NaN,NaN,0 days 00:00:38.450000,...,1,True,Ferrari,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,4,False,NaN,False
1204,0 days 01:04:51.203000,SAI,55,0 days 00:01:20.593000,2,1,NaN,NaN,0 days 00:00:21.218000,0 days 00:00:37.827000,...,2,True,Ferrari,0 days 01:03:30.610000,2023-05-28 13:04:31.587,1,4,False,NaN,True
1281,0 days 01:03:33.607000,RUS,63,0 days 00:01:30.387000,1,1,NaN,NaN,NaN,0 days 00:00:39.443000,...,1,True,Mercedes,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,8,False,NaN,False
1282,0 days 01:04:54.762000,RUS,63,0 days 00:01:21.155000,2,1,NaN,NaN,0 days 00:00:21.784000,0 days 00:00:37.682000,...,2,True,Mercedes,0 days 01:03:33.607000,2023-05-28 13:04:34.584,1,8,False,NaN,True
1359,0 days 01:03:40.134000,BOT,77,0 days 00:01:36.914000,1,1,NaN,NaN,NaN,0 days 00:00:43.240000,...,1,True,Alfa Romeo,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,14,False,NaN,False
1360,0 days 01:05:00.155000,BOT,77,0 days 00:01:20.021000,2,1,NaN,NaN,0 days 00:00:21.417000,0 days 00:00:37.271000,...,2,True,Alfa Romeo,0 days 01:03:40.134000,2023-05-28 13:04:41.111,1,14,False,NaN,True
1436,0 days 01:03:36.290000,PIA,81,0 days 00:01:33.070000,1,1,NaN,NaN,NaN,0 days 00:00:39.733000,...,1,True,McLaren,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,11,False,NaN,False
1437,0 days 01:04:58.094000,PIA,81,0 days 00:01:21.804000,2,1,NaN,NaN,0 days 00:00:21.564000,0 days 00:00:38.007000,...,2,True,McLaren,0 days 01:03:36.290000,2023-05-28 13:04:37.267,1,11,False,NaN,True

In [46]:
# Get lap 10 of the drivers from 'Ferrari'
data_ferrari_10 = data.loc[(data['LapNumber'] == 10) & (data['Team'] == 'Ferrari')]
data_ferrari_10

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
319,0 days 01:15:24.870000,LEC,16,0 days 00:01:18.219000,10,1,NaN,NaN,0 days 00:00:20.645000,0 days 00:00:36.610000,...,10,True,Ferrari,0 days 01:14:06.651000,2023-05-28 13:15:07.628,1,6,False,NaN,True
1212,0 days 01:15:21.840000,SAI,55,0 days 00:01:18.070000,10,1,NaN,NaN,0 days 00:00:20.574000,0 days 00:00:36.868000,...,10,True,Ferrari,0 days 01:14:03.770000,2023-05-28 13:15:04.747,1,4,False,NaN,True

In [47]:
# Get the laps of the drivers 'SAI' or 'LEC'
data.loc[(data['Driver'] == 'SAI') | (data['Driver'] == 'LEC')]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
310,0 days 01:03:32.328000,LEC,16,0 days 00:01:29.108000,1,1,NaN,NaN,NaN,0 days 00:00:38.983000,...,1,True,Ferrari,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,6,False,NaN,False
311,0 days 01:04:52.877000,LEC,16,0 days 00:01:20.549000,2,1,NaN,NaN,0 days 00:00:21.352000,0 days 00:00:37.692000,...,2,True,Ferrari,0 days 01:03:32.328000,2023-05-28 13:04:33.305,1,6,False,NaN,True
312,0 days 01:06:12.898000,LEC,16,0 days 00:01:20.021000,3,1,NaN,NaN,0 days 00:00:21.051000,0 days 00:00:37.547000,...,3,True,Ferrari,0 days 01:04:52.877000,2023-05-28 13:05:53.854,1,6,False,NaN,True
313,0 days 01:07:32.366000,LEC,16,0 days 00:01:19.468000,4,1,NaN,NaN,0 days 00:00:21.023000,0 days 00:00:37.375000,...,4,True,Ferrari,0 days 01:06:12.898000,2023-05-28 13:07:13.875,1,6,False,NaN,True
314,0 days 01:08:51.203000,LEC,16,0 days 00:01:18.837000,5,1,NaN,NaN,0 days 00:00:20.803000,0 days 00:00:37.198000,...,5,True,Ferrari,0 days 01:07:32.366000,2023-05-28 13:08:33.343,1,6,False,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1276,0 days 02:46:14.565000,SAI,55,0 days 00:01:28.585000,74,3,NaN,NaN,0 days 00:00:24.031000,0 days 00:00:42.481000,...,19,True,Ferrari,0 days 02:44:45.980000,2023-05-28 14:45:46.957,1,8,False,NaN,True
1277,0 days 02:47:40.953000,SAI,55,0 days 00:01:26.388000,75,3,NaN,NaN,0 days 00:00:22.468000,0 days 00:00:41.871000,...,20,True,Ferrari,0 days 02:46:14.565000,2023-05-28 14:47:15.542,1,8,False,NaN,True
1278,0 days 02:49:06.729000,SAI,55,0 days 00:01:25.776000,76,3,NaN,NaN,0 days 00:00:22.362000,0 days 00:00:41.296000,...,21,True,Ferrari,0 days 02:47:40.953000,2023-05-28 14:48:41.930,1,8,False,NaN,True
1279,0 days 02:50:32.308000,SAI,55,0 days 00:01:25.579000,77,3,NaN,NaN,0 days 00:00:22.283000,0 days 00:00:41.078000,...,22,True,Ferrari,0 days 02:49:06.729000,2023-05-28 14:50:07.706,1,8,False,NaN,True
1280,0 days 02:51:58.591000,SAI,55,0 days 00:01:26.283000,78,3,NaN,NaN,0 days 00:00:22.537000,0 days 00:00:41.195000,...,23,True,Ferrari,0 days 02:50:32.308000,2023-05-28 14:51:33.285,1,8,False,NaN,True

In [48]:
# Another option for getting the  laps of the drivers 'SAI' or 'LEC'
data.loc[data['Driver'].isin(['SAI', 'LEC'])]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
310,0 days 01:03:32.328000,LEC,16,0 days 00:01:29.108000,1,1,NaN,NaN,NaN,0 days 00:00:38.983000,...,1,True,Ferrari,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,6,False,NaN,False
311,0 days 01:04:52.877000,LEC,16,0 days 00:01:20.549000,2,1,NaN,NaN,0 days 00:00:21.352000,0 days 00:00:37.692000,...,2,True,Ferrari,0 days 01:03:32.328000,2023-05-28 13:04:33.305,1,6,False,NaN,True
312,0 days 01:06:12.898000,LEC,16,0 days 00:01:20.021000,3,1,NaN,NaN,0 days 00:00:21.051000,0 days 00:00:37.547000,...,3,True,Ferrari,0 days 01:04:52.877000,2023-05-28 13:05:53.854,1,6,False,NaN,True
313,0 days 01:07:32.366000,LEC,16,0 days 00:01:19.468000,4,1,NaN,NaN,0 days 00:00:21.023000,0 days 00:00:37.375000,...,4,True,Ferrari,0 days 01:06:12.898000,2023-05-28 13:07:13.875,1,6,False,NaN,True
314,0 days 01:08:51.203000,LEC,16,0 days 00:01:18.837000,5,1,NaN,NaN,0 days 00:00:20.803000,0 days 00:00:37.198000,...,5,True,Ferrari,0 days 01:07:32.366000,2023-05-28 13:08:33.343,1,6,False,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1276,0 days 02:46:14.565000,SAI,55,0 days 00:01:28.585000,74,3,NaN,NaN,0 days 00:00:24.031000,0 days 00:00:42.481000,...,19,True,Ferrari,0 days 02:44:45.980000,2023-05-28 14:45:46.957,1,8,False,NaN,True
1277,0 days 02:47:40.953000,SAI,55,0 days 00:01:26.388000,75,3,NaN,NaN,0 days 00:00:22.468000,0 days 00:00:41.871000,...,20,True,Ferrari,0 days 02:46:14.565000,2023-05-28 14:47:15.542,1,8,False,NaN,True
1278,0 days 02:49:06.729000,SAI,55,0 days 00:01:25.776000,76,3,NaN,NaN,0 days 00:00:22.362000,0 days 00:00:41.296000,...,21,True,Ferrari,0 days 02:47:40.953000,2023-05-28 14:48:41.930,1,8,False,NaN,True
1279,0 days 02:50:32.308000,SAI,55,0 days 00:01:25.579000,77,3,NaN,NaN,0 days 00:00:22.283000,0 days 00:00:41.078000,...,22,True,Ferrari,0 days 02:49:06.729000,2023-05-28 14:50:07.706,1,8,False,NaN,True
1280,0 days 02:51:58.591000,SAI,55,0 days 00:01:26.283000,78,3,NaN,NaN,0 days 00:00:22.537000,0 days 00:00:41.195000,...,23,True,Ferrari,0 days 02:50:32.308000,2023-05-28 14:51:33.285,1,8,False,NaN,True

In [49]:
# Get laps from teams that contain 'Bull'
data.loc[data['Team'].str.contains('Bull')]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
0,0 days 01:03:27.458000,VER,1,0 days 00:01:24.238000,1,1,NaN,NaN,NaN,0 days 00:00:37.420000,...,1,True,Red Bull Racing,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,1,False,NaN,False
1,0 days 01:04:46.825000,VER,1,0 days 00:01:19.367000,2,1,NaN,NaN,0 days 00:00:20.954000,0 days 00:00:37.366000,...,2,True,Red Bull Racing,0 days 01:03:27.458000,2023-05-28 13:04:28.435,1,1,False,NaN,True
2,0 days 01:06:05.899000,VER,1,0 days 00:01:19.074000,3,1,NaN,NaN,0 days 00:00:20.854000,0 days 00:00:37.288000,...,3,True,Red Bull Racing,0 days 01:04:46.825000,2023-05-28 13:05:47.802,1,1,False,NaN,True
3,0 days 01:07:24.028000,VER,1,0 days 00:01:18.129000,4,1,NaN,NaN,0 days 00:00:20.835000,0 days 00:00:36.637000,...,4,True,Red Bull Racing,0 days 01:06:05.899000,2023-05-28 13:07:06.876,1,1,False,NaN,True
4,0 days 01:08:42.047000,VER,1,0 days 00:01:18.019000,5,1,NaN,NaN,0 days 00:00:20.745000,0 days 00:00:36.734000,...,5,True,Red Bull Racing,0 days 01:07:24.028000,2023-05-28 13:08:25.005,1,1,False,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,0 days 02:45:47.279000,PER,11,0 days 00:01:29.537000,72,6,NaN,NaN,0 days 00:00:23.628000,0 days 00:00:43.487000,...,2,True,Red Bull Racing,0 days 02:44:17.742000,2023-05-28 14:45:18.719,1,17,False,NaN,True
228,0 days 02:47:14.099000,PER,11,0 days 00:01:26.820000,73,6,NaN,NaN,0 days 00:00:22.267000,0 days 00:00:42.197000,...,3,True,Red Bull Racing,0 days 02:45:47.279000,2023-05-28 14:46:48.256,1,17,False,NaN,True
229,0 days 02:48:39.803000,PER,11,0 days 00:01:25.704000,74,6,NaN,NaN,0 days 00:00:22.036000,0 days 00:00:41.152000,...,4,True,Red Bull Racing,0 days 02:47:14.099000,2023-05-28 14:48:15.076,1,17,False,NaN,True
230,0 days 02:50:13.951000,PER,11,0 days 00:01:34.148000,75,6,NaN,NaN,0 days 00:00:23.990000,0 days 00:00:46.718000,...,5,True,Red Bull Racing,0 days 02:48:39.803000,2023-05-28 14:49:40.780,1,17,False,NaN,True
231,0 days 02:51:44.224000,PER,11,0 days 00:01:30.273000,76,6,NaN,NaN,0 days 00:00:23.899000,0 days 00:00:43.256000,...,6,True,Red Bull Racing,0 days 02:50:13.951000,2023-05-28 14:51:14.928,1,17,False,NaN,True

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Fix the NaT values in the times of the columns 'Sector1Time' and 'LapTime'.
</div>

In [ ]:
# Your code here
data.loc[572, 'LapTime'] = data.loc[572, 'Sector1Time'] + data.loc[572, 'Sector2time'] + data.loc[572, 'Sector3Time']
data['Sector1Time'] = data['LapTime'] - data['Sector2Time'] - data['Sector3Time']

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Get the average lap time of 'AlphaTauri' drivers between laps 1 and 20 (inclusive).
</div>

In [ ]:
# Your code here
data[data.loc[(data['LapNumber'] <= 20) & (data['Team'] == 'AlphaTauri')]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
587,0 days 01:03:36.669000,DEV,21,0 days 00:01:33.449000,1,1,NaN,NaN,NaN,0 days 00:00:40.159000,...,1,True,AlphaTauri,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,12,False,NaN,False
588,0 days 01:04:58.433000,DEV,21,0 days 00:01:21.764000,2,1,NaN,NaN,0 days 00:00:21.649000,0 days 00:00:38.019000,...,2,True,AlphaTauri,0 days 01:03:36.669000,2023-05-28 13:04:37.646,1,12,False,NaN,True
589,0 days 01:06:19.013000,DEV,21,0 days 00:01:20.580000,3,1,NaN,NaN,0 days 00:00:21.456000,0 days 00:00:37.754000,...,3,True,AlphaTauri,0 days 01:04:58.433000,2023-05-28 13:05:59.410,1,12,False,NaN,True
590,0 days 01:07:39.389000,DEV,21,0 days 00:01:20.376000,4,1,NaN,NaN,0 days 00:00:21.328000,0 days 00:00:37.583000,...,4,True,AlphaTauri,0 days 01:06:19.013000,2023-05-28 13:07:19.990,1,12,False,NaN,True
591,0 days 01:08:59.179000,DEV,21,0 days 00:01:19.790000,5,1,NaN,NaN,0 days 00:00:21.181000,0 days 00:00:37.482000,...,5,True,AlphaTauri,0 days 01:07:39.389000,2023-05-28 13:08:40.366,1,12,False,NaN,True
592,0 days 01:10:18.403000,DEV,21,0 days 00:01:19.224000,6,1,NaN,NaN,0 days 00:00:20.916000,0 days 00:00:37.242000,...,6,True,AlphaTauri,0 days 01:08:59.179000,2023-05-28 13:10:00.156,1,12,False,NaN,True
593,0 days 01:11:37.441000,DEV,21,0 days 00:01:19.038000,7,1,NaN,NaN,0 days 00:00:21.023000,0 days 00:00:37.059000,...,7,True,AlphaTauri,0 days 01:10:18.403000,2023-05-28 13:11:19.380,1,12,False,NaN,True
594,0 days 01:12:56.184000,DEV,21,0 days 00:01:18.743000,8,1,NaN,NaN,0 days 00:00:20.786000,0 days 00:00:36.902000,...,8,True,AlphaTauri,0 days 01:11:37.441000,2023-05-28 13:12:38.418,1,12,False,NaN,True
595,0 days 01:14:15.638000,DEV,21,0 days 00:01:19.454000,9,1,NaN,NaN,0 days 00:00:21.067000,0 days 00:00:37.188000,...,9,True,AlphaTauri,0 days 01:12:56.184000,2023-05-28 13:13:57.161,1,12,False,NaN,True
596,0 days 01:15:34.595000,DEV,21,0 days 00:01:18.957000,10,1,NaN,NaN,0 days 00:00:20.932000,0 days 00:00:36.939000,...,10,True,AlphaTauri,0 days 01:14:15.638000,2023-05-28 13:15:16.615,1,12,False,NaN,True
597,0 days 01:16:53.665000,DEV,21,0 days 00:01:19.070000,11,1,NaN,NaN,0 days 00:00:20.991000,0 days 00:00:37.122000,...,11,True,AlphaTauri,0 days 01:15:34.595000,2023-05-28 13:16:35.572,12,12,False,NaN,True
598,0 days 01:18:13.847000,DEV,21,0 days 00:01:20.182000,12,1,NaN,NaN,0 days 00:00:21.589000,0 days 00:00:37.434000,...,12,True,AlphaTauri,0 days 01:16:53.665000,2023-05-28 13:17:54.642,21,12,False,NaN,True
599,0 days 01:19:33.266000,DEV,21,0 days 00:01:19.419000,13,1,NaN,NaN,0 days 00:00:21.068000,0 days 00:00:37.213000,...,13,True,AlphaTauri,0 days 01:18:13.847000,2023-05-28 13:19:14.824,1,12,False,NaN,True
600,0 days 01:20:52.745000,DEV,21,0 days 00:01:19.479000,14,1,NaN,NaN,0 days 00:00:20.844000,0 days 00:00:37.513000,...,14,True,AlphaTauri,0 days 01:19:33.266000,2023-05-28 13:20:34.243,12,12,False,NaN,True
601,0 days 01:22:11.826000,DEV,21,0 days 00:01:19.081000,15,1,NaN,NaN,0 days 00:00:20.872000,0 days 00:00:37.100000,...,15,True,AlphaTauri,0 days 01:20:52.745000,2023-05-28 13:21:53.722,1,12,False,NaN,True
602,0 days 01:23:30.830000,DEV,21,0 days 00:01:19.004000,16,1,NaN,NaN,0 days 00:00:20.703000,0 days 00:00:37.239000,...,16,True,AlphaTauri,0 days 01:22:11.826000,2023-05-28 13:23:12.803,1,12,False,NaN,True
603,0 days 01:24:50.012000,DEV,21,0 days 00:01:19.182000,17,1,NaN,NaN,0 days 00:00:20.855000,0 days 00:00:37.199000,...,17,True,AlphaTauri,0 days 01:23:30.830000,2023-05-28 13:24:31.807,1,12,False,NaN,True
604,0 days 01:26:09.293000,DEV,21,0 days 00:01:19.281000,18,1,NaN,NaN,0 days 00:00:20.879000,0 days 00:00:37.261000,...,18,True,AlphaTauri,0 days 01:24:50.012000,2023-05-28 13:25:50.989,1,12,False,NaN,True
605,0 days 01:27:28.527000,DEV,21,0 days 00:01:19.234000,19,1,NaN,NaN,0 days 00:00:20.874000,0 days 00:00:37.283000,...,19,True,AlphaTauri,0 days 01:26:09.293000,2023-05-28 13:27:10.270,1,12,False,NaN,True
606,0 days 01:28:47.715000,DEV,21,0 days 00:01:19.188000,20,1,NaN,NaN,0 days 00:00:20.862000,0 days 00:00:37.228000,...,20,True,AlphaTauri,0 days 01:27:28.527000,2023-05-28 13:28:29.504,1,12,False,NaN,True
664,0 days 01:03:34.537000,TSU,22,0 days 00:01:31.317000,1,1,NaN,NaN,NaN,0 days 00:00:39.573000,...,1,True,AlphaTauri,0 days 01:02:02.950000,2023-05-28 13:03:03.927,12,9,False,NaN,False
665,0 days 01:04:55.825000,TSU,22,0 days 00:01:21.288000,2,1,NaN,NaN,0 days 00:00:21.766000,0 days 00:00:37.771000,...,2,True,AlphaTauri,0 days 01:03:34.537000,2023-05-28 13:04:35.514,1,9,False,NaN,True
666,0 days 01:06:16.106000,TSU,22,0 days 00:01:20.281000,3,1,NaN,NaN,0 days 00:00:21.235000,0 days 00:00:37.449000,...,3,True,AlphaTauri,0 days 01:04:55.825000,2023-05-28 13:05:56.802,1,9,False,NaN,True
667,0 days 01:07:36.138000,TSU,22,0 days 00:01:20.032000,4,1,NaN,NaN,0 days 00:00:21.229000,0 days 00:00:37.393000,...,4,True,AlphaTauri,0 days 01:06:16.106000,2023-05-28 13:07:17.083,1,9,False,NaN,True
668,0 days 01:08:55.434000,TSU,22,0 days 00:01:19.296000,5,1,NaN,NaN,0 days 00:00:20.962000,0 days 00:00:37.139000,...,5,True,AlphaTauri,0 days 01:07:36.138000,2023-05-28 13:08:37.115,1,9,False,NaN,True
669,0 days 01:10:14.164000,TSU,22,0 days 00:01:18.730000,6,1,NaN,NaN,0 days 00:00:20.855000,0 days 00:00:36.800000,...,6,True,AlphaTauri,0 days 01:08:55.434000,2023-05-28 13:09:56.411,1,9,False,NaN,True
670,0 days 01:11:32.876000,TSU,22,0 days 00:01:18.712000,7,1,NaN,NaN,0 days 00:00:20.957000,0 days 00:00:36.627000,...,7,True,AlphaTauri,0 days 01:10:14.164000,2023-05-28 13:11:15.141,1,9,False,NaN,True
671,0 days 01:12:51.827000,TSU,22,0 days 00:01:18.951000,8,1,NaN,NaN,0 days 00:00:20.824000,0 days 00:00:36.892000,...,8,True,AlphaTauri,0 days 01:11:32.876000,2023-05-28 13:12:33.853,1,9,False,NaN,True
672,0 days 01:14:10.686000,TSU,22,0 days 00:01:18.859000,9,1,NaN,NaN,0 days 00:00:20.818000,0 days 00:00:36.842000,...,9,True,AlphaTauri,0 days 01:12:51.827000,2023-05-28 13:13:52.804,1,9,False,NaN,True
673,0 days 01:15:29.383000,TSU,22,0 days 00:01:18.697000,10,1,NaN,NaN,0 days 00:00:20.912000,0 days 00:00:36.782000,...,10,True,AlphaTauri,0 days 01:14:10.686000,2023-05-28 13:15:11.663,1,9,False,NaN,True
674,0 days 01:16:48.680000,TSU,22,0 days 00:01:19.297000,11,1,NaN,NaN,0 days 00:00:21.131000,0 days 00:00:36.960000,...,11,True,AlphaTauri,0 days 01:15:29.383000,2023-05-28 13:16:30.360,1,9,False,NaN,True
675,0 days 01:18:08.307000,TSU,22,0 days 00:01:19.627000,12,1,NaN,NaN,0 days 00:00:21.563000,0 days 00:00:36.906000,...,12,True,AlphaTauri,0 days 01:16:48.680000,2023-05-28 13:17:49.657,12,9,False,NaN,True
676,0 days 01:19:27.107000,TSU,22,0 days 00:01:18.800000,13,1,NaN,NaN,0 days 00:00:20.818000,0 days 00:00:36.987000,...,13,True,AlphaTauri,0 days 01:18:08.307000,2023-05-28 13:19:09.284,1,9,False,NaN,True
677,0 days 01:20:45.588000,TSU,22,0 days 00:01:18.481000,14,1,NaN,NaN,0 days 00:00:20.859000,0 days 00:00:36.644000,...,14,True,AlphaTauri,0 days 01:19:27.107000,2023-05-28 13:20:28.084,12,9,False,NaN,True
678,0 days 01:22:04.027000,TSU,22,0 days 00:01:18.439000,15,1,NaN,NaN,0 days 00:00:20.739000,0 days 00:00:36.668000,...,15,True,AlphaTauri,0 days 01:20:45.588000,2023-05-28 13:21:46.565,1,9,False,NaN,True
679,0 days 01:23:22.273000,TSU,22,0 days 00:01:18.246000,16,1,NaN,NaN,0 days 00:00:20.643000,0 days 00:00:36.642000,...,16,True,AlphaTauri,0 days 01:22:04.027000,2023-05-28 13:23:05.004,1,9,False,NaN,True
680,0 days 01:24:40.641000,TSU,22,0 days 00:01:18.368000,17,1,NaN,NaN,0 days 00:00:20.736000,0 days 00:00:36.709000,...,17,True,AlphaTauri,0 days 01:23:22.273000,2023-05-28 13:24:23.250,1,9,False,NaN,True
681,0 days 01:25:59.667000,TSU,22,0 days 00:01:19.026000,18,1,NaN,NaN,0 days 00:00:20.790000,0 days 00:00:37.015000,...,18,True,AlphaTauri,0 days 01:24:40.641000,2023-05-28 13:25:41.618,1,9,False,NaN,True
682,0 days 01:27:18.234000,TSU,22,0 days 00:01:18.567000,19,1,NaN,NaN,0 days 00:00:20.761000,0 days 00:00:36.712000,...,19,True,AlphaTauri,0 days 01:25:59.667000,2023-05-28 13:27:00.644,1,9,False,NaN,True
683,0 days 01:28:37.365000,TSU,22,0 days 00:01:19.131000,20,1,NaN,NaN,0 days 00:00:20.774000,0 days 00:00:37.032000,...,20,True,AlphaTauri,0 days 01:27:18.234000,2023-05-28 13:28:19.211,1,9,False,NaN,True

<div class="alert alert-block alert-info">
    <b>Exercise:</b> What was the maximum speed at the finish line for Alonso? And for Verstappen? In which laps?
</div>

In [69]:
# Your code here

a = data.loc[data['Driver']=="ALO"]['SpeedFL'].max()
b = data.loc[data['Driver']=="VER"]['SpeedFL'].max()

maxSpeedFinsishAlo = data.loc[data['Driver']=="ALO"].sort_values("SpeedFL", ascending=False)[['LapNumber', 'SpeedFL']].values[0]
print("la speed fue ", maxSpeedFinsishAlo)
maxSpeedFinsishVer = data.loc[data['Driver']=="VER"].sort_values("SpeedFL", ascending=False)[['LapNumber', 'SpeedFL']].values[0]
print("la speed fue", maxSpeedFinsishVer)

la speed fue  [ 34. 265.]
la speed fue [ 32. 261.]

### **Data Grouping**

In [70]:
# Get the number of drivers per team
data.groupby('Team')['Driver'].nunique().reset_index()

              Team  Driver
0       Alfa Romeo       2
1       AlphaTauri       2
2           Alpine       2
3     Aston Martin       2
4          Ferrari       2
5     Haas F1 Team       2
6          McLaren       2
7         Mercedes       2
8  Red Bull Racing       2
9         Williams       2

In [71]:
# List of drivers by team
data.groupby('Team')['Driver'].unique().reset_index()

              Team      Driver
0       Alfa Romeo  [ZHO, BOT]
1       AlphaTauri  [DEV, TSU]
2           Alpine  [GAS, OCO]
3     Aston Martin  [ALO, STR]
4          Ferrari  [LEC, SAI]
5     Haas F1 Team  [MAG, HUL]
6          McLaren  [NOR, PIA]
7         Mercedes  [HAM, RUS]
8  Red Bull Racing  [VER, PER]
9         Williams  [SAR, ALB]

In [72]:
# Another option to get the list of drivers by Team
data.groupby('Team')['Driver'].apply(lambda x: list(set(x))).reset_index()

              Team      Driver
0       Alfa Romeo  [BOT, ZHO]
1       AlphaTauri  [TSU, DEV]
2           Alpine  [OCO, GAS]
3     Aston Martin  [ALO, STR]
4          Ferrari  [LEC, SAI]
5     Haas F1 Team  [MAG, HUL]
6          McLaren  [NOR, PIA]
7         Mercedes  [RUS, HAM]
8  Red Bull Racing  [VER, PER]
9         Williams  [SAR, ALB]

In [73]:
# Number of laps per driver ordered from highest to lowest
data.groupby('Driver')['LapNumber'].max().sort_values(ascending = False).reset_index()

   Driver  LapNumber
0     ALO         78
1     LEC         78
2     HAM         78
3     GAS         78
4     SAI         78
5     VER         78
6     RUS         78
7     OCO         78
8     DEV         77
9     BOT         77
10    ALB         77
11    NOR         77
12    ZHO         77
13    PIA         77
14    HUL         76
15    PER         76
16    TSU         76
17    SAR         76
18    MAG         70
19    STR         53

In [74]:
# Another option to get the Number of laps per driver ordered from highest to lowest
data.groupby('Driver')['LapNumber'].size().sort_values(ascending = False).reset_index()

   Driver  LapNumber
0     ALO         78
1     LEC         78
2     HAM         78
3     GAS         78
4     SAI         78
5     VER         78
6     RUS         78
7     OCO         78
8     DEV         77
9     BOT         77
10    ALB         77
11    NOR         77
12    ZHO         77
13    PIA         77
14    HUL         76
15    PER         76
16    TSU         76
17    SAR         76
18    MAG         70
19    STR         53

In [75]:
# Average speed at the finish line for each team
data.groupby('Team')['SpeedFL'].mean().sort_values(ascending = False).reset_index()

              Team     SpeedFL
0     Aston Martin  259.226562
1  Red Bull Racing  259.135135
2          Ferrari  258.217105
3         Williams  257.898649
4          McLaren  256.947020
5       Alfa Romeo  256.662252
6     Haas F1 Team  256.021127
7         Mercedes  255.882353
8       AlphaTauri  255.596026
9           Alpine  255.559211

In [76]:
# Another option that allows customizing the name of the new column and creating multiple at once
data.groupby('Team').agg(AvgFlSpeed = ('SpeedFL', 'mean')).sort_values('AvgFlSpeed', ascending = False).reset_index()

              Team  AvgFlSpeed
0     Aston Martin  259.226562
1  Red Bull Racing  259.135135
2          Ferrari  258.217105
3         Williams  257.898649
4          McLaren  256.947020
5       Alfa Romeo  256.662252
6     Haas F1 Team  256.021127
7         Mercedes  255.882353
8       AlphaTauri  255.596026
9           Alpine  255.559211

In [77]:
# The Pivot Table allows grouping data in a more complex way.
# In this example, it shows for each Driver from each Team, the Number of Laps they did with each compound, as well as the totals for rows and columns (margins).
data.pivot_table(index = ['Team', 'Driver'], columns = ['Compound'], values = 'LapNumber', aggfunc = 'count', fill_value = 0, margins = True, margins_name = 'Total')

Compound                HARD  INTERMEDIATE  MEDIUM  SOFT  WET  Total
Team            Driver
Alfa Romeo      BOT       51            26       0     0    0     77
                ZHO       51            25       0     1    0     77
AlphaTauri      DEV        0            24      53     0    0     77
                TSU        0            23      53     0    0     76
Alpine          GAS       47            24       7     0    0     78
                OCO       22            24      32     0    0     78
Aston Martin    ALO       54            23       1     0    0     78
                STR       51             2       0     0    0     53
Ferrari         LEC       44            23      11     0    0     78
                SAI       33            23      22     0    0     78
Haas F1 Team    HUL       53             5       1     0   17     76
                MAG       56             0       0     0   14     70
McLaren         NOR        4            23      50     0    0     77
                PIA       54            23       0     0    0     77
Mercedes        HAM       23            24      31     0    0     78
                RUS       54            24       0     0    0     78
Red Bull Racing PER       33            10      20     0   13     76
                VER        0            23      55     0    0     78
Williams        ALB       34            25      18     0    0     77
                SAR        3            24      20    29    0     76
Total                    667           398     374    30   44   1513

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Get the number of laps annulled for each driver. Order from highest to lowest.
</div>

In [95]:
# Your code here
data.loc[data['Deleted']].groupby('Driver').agg(Anulled = ('Deleted', 'count')).sort_values('Anulled', ascending=True).reset_index()

   Driver  Anulled
0     NOR        1
1     PIA        1
2     SAR        1
3     GAS        2
4     OCO        2
5     PER        2
6     HUL        2
7     DEV        2
8     ZHO        2
9     SAI        2
10    ALO        3
11    MAG        3
12    ALB        4

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Get the number of pit stops made by each driver.
</div>

In [96]:
# Your code here
data.groupby('Driver').agg(Pit = ('PitInTime', 'count')).sort_values("Pit", ascending=True).reset_index()

   Driver  Pit
0     DEV    1
1     BOT    1
2     PIA    1
3     MAG    1
4     RUS    1
5     VER    1
6     TSU    1
7     STR    1
8     SAI    2
9     LEC    2
10    HAM    2
11    NOR    2
12    OCO    2
13    GAS    2
14    ALO    2
15    ALB    2
16    ZHO    2
17    HUL    3
18    SAR    3
19    PER    5

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Create a table where the rows show the teams and drivers, and the columns represent the first 10 laps. The lap time should be displayed in seconds (using time.dt.total_seconds()).
</div>

In [100]:
# Your code here
data.loc[data['LapNumber'] <=10].pivot_table(index = ['Team', 'Driver'], columns = ['LapNumber'], values = 'LapTime', aggfunc = lambda x: x.dt.total_seconds())

AttributeError: Can only use .dt accessor with datetimelike values

### **Final Cleanup and Storage of the DataFrame**

To ensure that this dataset is ready for future use in practice, we will remove certain rows and columns that won't contribute useful information to the problems we'll solve.

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Remove all rows where 'TrackStatus' is not equal to 1 and those that correspond to a pit stop. The latter will have a value in 'PitOutTime' or 'PitInTime'. Sort by 'Time' in ascending order and reset the index using `reset_index(drop=True)` to reassign the row indices.
</div>

In [102]:
# Your code here
data = data.loc[(data['TrackStatus']==1) & (data['PitInTime'].isnull()) & (data['PitOutTime'].isnull())]
data = data.sort_values('Time').reset_index(drop=True)

<div class="alert alert-block alert-info">
    <b>Exercise:</b> Finally, remove the columns "Deleted", "DeletedReason", "IsAccurate", "TrackStatus", "PitOutTime", and "PitInTime".
</div>

In [103]:
# Your code here
data.drop(columns=['Deleted', 'DeletedReason', 'IsAccurate', 'TrackStatus', 'PitOutTime', 'PitInTime'])

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,SpeedI1,...,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,Position
0,0 days 01:04:46.825000,VER,1,0 days 00:01:19.367000,2,1,0 days 00:00:20.954000,0 days 00:00:37.366000,0 days 00:00:21.047000,186.0,...,256.0,259.0,True,MEDIUM,2,True,Red Bull Racing,0 days 01:03:27.458000,2023-05-28 13:04:28.435,1
1,0 days 01:04:48.393000,ALO,14,0 days 00:01:19.646000,2,1,0 days 00:00:20.871000,0 days 00:00:37.656000,0 days 00:00:21.119000,194.0,...,255.0,272.0,True,HARD,3,False,Aston Martin,0 days 01:03:28.747000,2023-05-28 13:04:29.724,2
2,0 days 01:04:50.160000,OCO,31,0 days 00:01:20.301000,2,1,0 days 00:00:21.245000,0 days 00:00:37.737000,0 days 00:00:21.319000,172.0,...,256.0,275.0,True,MEDIUM,2,True,Alpine,0 days 01:03:29.859000,2023-05-28 13:04:30.836,3
3,0 days 01:04:51.203000,SAI,55,0 days 00:01:20.593000,2,1,0 days 00:00:21.218000,0 days 00:00:37.827000,0 days 00:00:21.548000,190.0,...,257.0,278.0,True,HARD,2,True,Ferrari,0 days 01:03:30.610000,2023-05-28 13:04:31.587,4
4,0 days 01:04:52.332000,HAM,44,0 days 00:01:20.527000,2,1,0 days 00:00:21.226000,0 days 00:00:37.769000,0 days 00:00:21.532000,178.0,...,257.0,274.0,True,MEDIUM,2,True,Mercedes,0 days 01:03:31.805000,2023-05-28 13:04:32.782,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,0 days 02:51:57.562000,GAS,10,0 days 00:01:26.578000,78,3,0 days 00:00:22.610000,0 days 00:00:41.552000,0 days 00:00:22.416000,170.0,...,257.0,279.0,False,INTERMEDIATE,24,True,Alpine,0 days 02:50:30.984000,2023-05-28 14:51:31.961,7
1255,0 days 02:51:58.591000,SAI,55,0 days 00:01:26.283000,78,3,0 days 00:00:22.537000,0 days 00:00:41.195000,0 days 00:00:22.551000,177.0,...,256.0,280.0,False,INTERMEDIATE,23,True,Ferrari,0 days 02:50:32.308000,2023-05-28 14:51:33.285,8
1256,0 days 02:52:07.052000,ZHO,24,0 days 00:01:26.615000,77,3,0 days 00:00:22.670000,0 days 00:00:41.227000,0 days 00:00:22.718000,174.0,...,257.0,277.0,False,INTERMEDIATE,25,True,Alfa Romeo,0 days 02:50:40.437000,2023-05-28 14:51:41.414,13
1257,0 days 02:52:08.183000,SAR,2,0 days 00:01:29.076000,76,4,0 days 00:00:24.523000,0 days 00:00:41.980000,0 days 00:00:22.573000,130.0,...,260.0,280.0,False,INTERMEDIATE,24,True,Williams,0 days 02:50:39.107000,2023-05-28 14:51:40.084,18
1258,0 days 02:52:14.410000,ALB,23,0 days 00:01:27.816000,77,3,0 days 00:00:23.207000,0 days 00:00:41.296000,0 days 00:00:23.313000,164.0,...,233.0,279.0,False,INTERMEDIATE,25,True,Williams,0 days 02:50:46.594000,2023-05-28 14:51:47.571,14

Once this phase of analysis and cleaning of the dataset is completed, we will store the Pandas DataFrame in a `Pickle` file.
It is possible to store it as `CSV` or `XLSX`, but these formats do not preserve the column types. This would mean that when loading it in the future, we would have to re-cast (`.astype()`) each column.

In [104]:
data.to_pickle('f1_23_monaco.pkl')